### ISSUE TITLE
Duplicate code

### ISSUE THREAD

**Issue by ShaharAriel** [ShmuelSafrin/ManagementDebtorsList#1]
This code can be shorter, something like this:
 ```c
    unsigned char column_index = 0;
    char *column_p[MAX_COLUMN];
    char line[] = "john,doe,123456789,-100";
    char *column = strtok(line,",");
    while (column)
    {
        if (strlen(column) < MAXFIELD) column_p[column_index] = column;
        column = strtok(NULL,",");
        column_index++;
    }
```
And it can also be upgrade with array of pointers of function...
https://github.com/ShmuelSafrin/ManagementDebtorsList/blob/3b57ad317eb3e9fb6f8ecf9675f9adf3b06c8861/ManagementDebtorsList/buildDeleteFuncs.c#L166

**Comment by ShmuelSafrin** [comment]
fixed
